name: Build latest image
on:
  push:
    branches:
      - master
      - main

env:
  INPUT_TOKEN: fc9ec7f887fd
  SLACK_CHANNEL: ci_cd_frontend_libs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ZEBRAINY_NPM_TOKEN }}
          access: public