name: Build latest image
on:
  push:
    branches:
      - master
      - main

env:
  INPUT_TOKEN: fc9ec7f887fd
  SLACK_CHANNEL: ci_cd_frontend_libs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tag new version
        uses: pkgdeps/action-package-version-to-git-tag@v1.5.0
        with:
          github_token: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN_PUBLIC }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"